plugins:
  - jekyll-feed

include:
  - .htaccess
  - _pages

exclude:
  - pat.py
  - prepare_score_pages.py

theme: minimal-mistakes-jekyll
minimal_mistakes_skin    : "contrast"


# site settings
locale                   : "en-US"
title                    : Edition Esser-Skala
title_separator          : "-"
subtitle                 :
name                     : Wolfgang Esser-Skala
description              : Open-source music publishing since 2016.
url                      : https://edition.esser-skala.at
baseurl                  : ""
repository               : edition-esser-skala/webpage
logo                     : /assets/images/logo_full_bg_white.png
breadcrumbs              : false
atom_feed:
  path                   : # blank (default) uses feed.xml
  hide                   : true
search                   : true
search_full_content      : true
search_provider          : lunr
date_format              : "%A, %-d %B %Y"


# social sharing
twitter:
  username               : skafdasschaf
social:
  type                   : Person
  links:
    - https://twitter.com/skafdasschaf
    - https://www.facebook.com/wolfgang.esser.skala
    - https://linkedin.com/in/wolfgang-esser-skala


# site author
author:
  name             : Wolfgang Esser-Skala
  avatar           : assets/images/avatar.jpg
  bio              : Editor
  email            : edition@esser-skala.at


# site footer
footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      # url:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      # url:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      # url:
    - label: "GitLab"
      icon: "fab fa-fw fa-gitlab"
      # url:
    - label: "Bitbucket"
      icon: "fab fa-fw fa-bitbucket"
      # url:
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      # url:

# general
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# markdown processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed


# outputting
permalink: /news/:year/:month/:day/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: Europe/Vienna


category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/


# defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false

  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      show_date: true
      read_time: false
      comments: false
      share: true
      related: false

after_footer_scripts:
  - https://cdn.datatables.net/1.11.3/js/jquery.dataTables.js
  - /assets/js/format_toctable.js
