name: Build and deploy site

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 1"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get app token
        id: get_app_token
        uses: peter-murray/workflow-application-token-action@v1
        with:
          application_id: ${{ secrets.APPLICATION_ID }}
          application_private_key: ${{ secrets.APPLICATION_PRIVATE_KEY }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install GitPython pandas PyGithub Pygments python-dateutil strictyaml

      - name: Generate pages
        env:
          GH_API_TOKEN: ${{ steps.get_app_token.outputs.token }}
        run: |
          mkdir -p _data _pages/projects _pages/scores
          python _plugins/page_generator.py

      - name: Build webpage
        uses: jerryjvl/jekyll-build-action@v1

      - name: Deploy via rsync
        uses: burnett01/rsync-deployments@5.2
        with:
          switches: -avzr --delete --exclude=/assets/pdf/
          path: _site/
          remote_path: html/edition/
          remote_host: ${{ secrets.DEPLOY_HOST }}
          remote_user: ${{ secrets.DEPLOY_USER }}
          remote_key: ${{ secrets.DEPLOY_KEY }}
